### ISSUE TITLE
ADCP Method [delete unnecessary details for new measurement]

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#11]
Salam yakob,

untuk ADCP method, minta yakkob delete unnecessary details seperti highlight merah.

data tersebut tidak diperlukan untuk user key in.

![image](https://user-images.githubusercontent.com/49171338/56267507-94d03980-6121-11e9-8661-75919a40c8b7.png)

http://rcsd.costcut.co:4000/adcps/new

@abigoroth

**Comment by azlinda8330** [comment]
![image](https://user-images.githubusercontent.com/49171338/56267583-cf39d680-6121-11e9-8df2-4e7a2c68b015.png)


@abigoroth

**Comment by abigoroth** [comment]
noted lin.

**Comment by abigoroth** [comment]
<img width="720" alt="RCSD" src="https://user-images.githubusercontent.com/520990/56396669-82194a00-6272-11e9-8484-c23019896b0d.png">

@azlinda8330 saya dah remove unnecessary field..

**Comment by abigoroth** [comment]
@azlinda8330 yang ni dah check ke? boleh close klau dah

**Comment by azlinda8330** [comment]
close
