### ISSUE TITLE
Float Method [Error]

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#12]
Salam Yakob,

Terdapat error pada Float Method. 

Identified as "ajax error"

![image](https://user-images.githubusercontent.com/49171338/56267999-f5ac4180-6122-11e9-8042-ccb403ec6953.png)

**Comment by azlinda8330** [comment]
yakob tolong betul kan label berikut untuk float method

![image](https://user-images.githubusercontent.com/49171338/56268271-81be6900-6123-11e9-8591-6fe90c35df5f.png)


@abigoroth

**Comment by azlinda8330** [comment]
![image](https://user-images.githubusercontent.com/49171338/56269933-8a18a300-6127-11e9-9f96-7f414ef929fe.png)


lepas ley in data lin tekan save. 

lepas tu nak tengok result tak boleh. ada Error.

![image](https://user-images.githubusercontent.com/49171338/56269997-b59b8d80-6127-11e9-8739-2ee10417efc2.png)

**Comment by abigoroth** [comment]
<img width="720" alt="RCSD" src="https://user-images.githubusercontent.com/520990/56396416-4467f180-6271-11e9-8034-681da579a2d9.png">

lin please re-try, its broken because of previously 18-mac uncompleted data. @azlinda8330

**Comment by abigoroth** [comment]
@azlinda8330 yang ni dah test ke ?

**Comment by azlinda8330** [comment]
dah close okay
