### ISSUE TITLE
Overlay Rating Curve (RC) with Master Cross-section (CS)

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#14]
Salam Yakob,

Ni file yang Overlay RC with CS. Lin buat untuk Sg. Bernam tahun 2018.

[Overlay Sg Bernam (2018).xlsx](https://github.com/abigoroth/rcsd/files/3097519/Overlay.Sg.Bernam.2018.xlsx)

**Comment by azlinda8330** [comment]
ni file JPS untuk sg golok method ADCP

[Overlay_Chart in Microsoft Word.xlsx](https://github.com/abigoroth/rcsd/files/3099554/Overlay_Chart.in.Microsoft.Word.xlsx)

**Comment by azlinda8330** [comment]
@abigoroth

**Comment by azlinda8330** [comment]
yang ni Sg Golok ADCP yang lin buat untuk 2018

[Overlay Sg Golok ADCP (2018).xlsx](https://github.com/abigoroth/rcsd/files/3099555/Overlay.Sg.Golok.ADCP.2018.xlsx)

**Comment by abigoroth** [comment]
https://docs.anychart.com/Axes_and_Grids/Additional_Axes

**Comment by abigoroth** [comment]
https://www.anychart.com/buy/
