### ISSUE TITLE
[Export to Excel] function

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#15]
Yakob,

We need to add 'Export to Excel' function below the rating rating table.

It should carry the Stage, H value, Discharge, Q (Polynomial Function) and Discharge, Q (Power function).

@abigoroth

**Comment by abigoroth** [comment]
<img width="720" alt="RCSD" src="https://user-images.githubusercontent.com/520990/56477378-69f63480-64d7-11e9-96c3-e01595dd4aab.png">

<img width="720" alt="RCSD" src="https://user-images.githubusercontent.com/520990/56477391-85613f80-64d7-11e9-90c2-19a5c899e790.png">

@azlinda8330

**Comment by azlinda8330** [comment]
close
