### ISSUE TITLE
UAT 2

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/rcsd#16]
- [ ] 1. Cross Section - unable to edit value.
- [ ] 2. Sediment Discharge - rating curve problem.
- [ ] 3. Create user management, with password control
- [ ] 4. technician to see analyze too

**Comment by abigoroth** [comment]
@azlinda8330 sy nak buat no 2 pulak, no 1 saya dah siap.. nanti nak kena test.

**Comment by azlinda8330** [comment]
Salam Yakob,

Untuk VA Method, ingat tak yang Brother Cina tu dia minta kita automasi kan nilai Duration untuk 50 s bila kita refresh untuk Flow Depth, table akan generate measurement method at 0.6 Y atau 0.2 Y atau 0.8Y.

![image](https://user-images.githubusercontent.com/49171338/56776416-d1c1bd80-67fe-11e9-8028-2168fc3619ec.png)

**Comment by azlinda8330** [comment]
Untuk Master Cross Section,

Tolong tukar perkataan Width ke Distance.

![image](https://user-images.githubusercontent.com/49171338/56777161-85787c80-6802-11e9-8dfa-dc690c9bfa7a.png)

**Comment by azlinda8330** [comment]
all cleared. close
