### ISSUE TITLE
UAT 2: RADAR METHOD IMPROVEMENT

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#17]
Terdapat beberapa issues dengan radar method.

1. Yakob tolong delete kan yang saya tanda dengan kotak merah.

![image](https://user-images.githubusercontent.com/49171338/56741247-10c32500-67a5-11e9-91a4-e7563957eb2d.png)

2. Bawah ni button "Back" ada 2 kali.

Delete satu.

![image](https://user-images.githubusercontent.com/49171338/56741282-28021280-67a5-11e9-9ade-aa298d1a3f62.png)

@abigoroth

**Comment by azlinda8330** [comment]
error generate rating curve for radar method

http://rcsd.costcut.co:4000/radars/rating_table?filter%5Bfrom_year%5D=2016&filter%5Bstage_max%5D=4.293&filter%5Bstage_min%5D=3.199&filter%5Bstation_id%5D=14&filter%5Bto_year%5D=2016



![image](https://user-images.githubusercontent.com/49171338/56747919-6a315100-67b1-11e9-84f1-ff0596de0cec.png)

**Comment by azlinda8330** [comment]
SORRY yang issue error di atas dah fixed, tadi saya masuk guna acc technician memanglah tak leh generate rating curve.
Sorry yakob. Dah dapat dah guna Admin

**Comment by abigoroth** [comment]
@azlinda8330 anyway memang ada request untuk technician kan?

**Comment by abigoroth** [comment]
@azlinda8330 boleh check n close issue ni klau ok

**Comment by azlinda8330** [comment]
Okay Close
