### ISSUE TITLE
UAT 2: SEDIMENT DISCHARGE

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#18]
1. To create an option in the Sediment Measurement Form for the technician to select Discharge Station in order for the system to automatic search the Discharge, Q value.

2. To incorporate the Discharge value into the Calculation.

3. To sort the date of the key in data. the data below are not sorted according to 2 dates, namely 4/April/2017 and 4/July/2017

@abigoroth 

![image](https://user-images.githubusercontent.com/49171338/56779136-2455a680-680c-11e9-9a39-5a575cd677d1.png)

**Comment by azlinda8330** [comment]
![image](https://user-images.githubusercontent.com/49171338/56779191-5b2bbc80-680c-11e9-9e97-ae73c4a2dd24.png)

**Comment by abigoroth** [comment]
@azlinda8330 boleh close yg ni?

**Comment by azlinda8330** [comment]
Boleh close
