### ISSUE TITLE
[radar] system error because of emptied left field

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/rcsd#2]
- [x] validations all field
- [x] column guide untuk paste from excel

**Comment by abigoroth** [comment]
![image](https://user-images.githubusercontent.com/520990/55363029-5f670180-550e-11e9-9c43-4b08954e45c5.png)
@azlinda8330

**Comment by azlinda8330** [comment]
1. Validations all field  [**agree**]

 2. Column guide untuk paste from excel [**agree**]

**Comment by abigoroth** [comment]
![image](https://user-images.githubusercontent.com/520990/55365479-47e04680-5517-11e9-9368-d085bfad86c0.png)

**Comment by azlinda8330** [comment]
okay cun!

**Comment by azlinda8330** [comment]
en yakob boleh pindah kan button New Radar ke atas dan Label as New Radar Measurement


![image](https://user-images.githubusercontent.com/49171338/55638746-7f424200-57fa-11e9-8c81-964b77501660.png)

**Comment by azlinda8330** [comment]
En Yakob,

Lin tengah masukkan data Sg. Segamat 2016 untuk radar. So far plot generate Stage Height, H versus Discharge, Q okay. Sama dengan MS Excel saya.

Tetapi bila generate rating, kalau en yakob tengok value minimum stage height ialah 3.199 dan maksimum adalah 4.293. Tapi bila clikc generate rating, value yang digenerate melebihi maximum yang dikehendaki mengakibatkan ada value negative bagi plot polynomial.

Mohon yakob tengok kembali. tengok pada generate rating curve dia dah overpredict daripada yang sepatutnya.

![image](https://user-images.githubusercontent.com/49171338/55640109-8c146500-57fd-11e9-9d38-20ba8fedddc5.png)

**Comment by abigoroth** [comment]
@azlinda8330 lin copy create issue lain, ni issue yang page broken, tak boleh bukak. create specific issue
