### ISSUE TITLE
Technician Sediment Discharge Analyze

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/rcsd#21]
- [ ] without rating curve
- [ ] without formula

**Comment by azlinda8330** [comment]
Salam yakob,

kita agree ye technician boleh view graph yang yakob plot tu ye

paksi Y = Discharge, Q (m3/s)

paksi x = Total Product Ss.Q (m3/s)

**Comment by abigoroth** [comment]
@azlinda8330 boleh test dah yg ni

**Comment by azlinda8330** [comment]
@abigoroth  okay checked. dah boleh close kan
