### ISSUE TITLE
[user manual] User can edit directly from the table if they select both the same year (from-to) 

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/rcsd#22]
this requirement is requested by en Hafiz.

<img width="714" alt="RCSD" src="https://user-images.githubusercontent.com/520990/57117556-84f65d80-6d8f-11e9-838a-cd040b747cfe.png">

**Comment by abigoroth** [comment]
relate to #20

**Comment by azlinda8330** [comment]
function requested worked. checked.
