### ISSUE TITLE
Correction on RCSD system

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#26]
Salam Yakob please make necessary corrections asap.

1. This should be "New Float Method Measurement"

![image](https://user-images.githubusercontent.com/49171338/57581057-e2578080-74ec-11e9-912b-3b3247c10bbe.png)

**Comment by azlinda8330** [comment]
2. This should be Radar Method

![image](https://user-images.githubusercontent.com/49171338/57581074-1632a600-74ed-11e9-8b42-67fe386cf072.png)

**Comment by azlinda8330** [comment]
3. This should be "New Radar Measurement"

![image](https://user-images.githubusercontent.com/49171338/57581081-467a4480-74ed-11e9-8307-21e7ea7c4210.png)

**Comment by abigoroth** [comment]
@azlinda8330 dah fix.. boleh close klau dah ok

**Comment by azlinda8330** [comment]
close
