### ISSUE TITLE
technician many station

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/rcsd#4]
- [x] seed new technician-list and link to station
- [x] form station selection
- [x] scope at filter
- [x] display station filter for technician
- [ ] create controller

**Comment by abigoroth** [comment]
Station.by_user(user)

**Comment by azlinda8330** [comment]
Done ke en yakob?

**Comment by abigoroth** [comment]
<img width="394" alt="RCSD" src="https://user-images.githubusercontent.com/520990/55647343-02ba5e00-5810-11e9-84ae-d265671a8316.png">

@azlinda8330 baru siap seed data & link dengan station
