### ISSUE TITLE
[radar] Rating Curve plot for Radar Method (polynomial function)

### ISSUE THREAD

**Issue by azlinda8330** [abigoroth/rcsd#5]
En Yakob,

Lin tengah masukkan data Sg. Segamat 2016 untuk radar. So far plot generate Stage Height, H versus Discharge, Q okay. Sama dengan MS Excel saya.

Tetapi bila generate rating, kalau en yakob tengok value minimum stage height ialah 3.199 dan maksimum adalah 4.293. Tapi bila clikc generate rating, value yang digenerate melebihi maximum yang dikehendaki mengakibatkan ada value negative bagi plot polynomial.

Mohon yakob tengok kembali. tengok pada generate rating curve dia dah overpredict daripada yang sepatutnya.

![image](https://user-images.githubusercontent.com/49171338/55718939-87cf8e00-5a2f-11e9-937c-809bd94a715d.png)

**Comment by abigoroth** [comment]
@azlinda8330 close this issue

**Comment by abigoroth** [comment]
please @azlinda8330

**Comment by azlinda8330** [comment]
okay this one is settled.
