### ISSUE TITLE
[va method] cross section count follows river width

### ISSUE THREAD

**Issue by abigoroth** [abigoroth/rcsd#9]

**Comment by abigoroth** [comment]
@azlinda8330 ingat tak issue ni.

**Comment by azlinda8330** [comment]
Ingat. 
Ini untuk generate no. of verticals tu ker?

**Comment by azlinda8330** [comment]
Yakob dah start buat issue ni ke belum?

**Comment by abigoroth** [comment]
sy dah siapkan.. cbe test @azlinda8330

**Comment by azlinda8330** [comment]
okay 
will test

**Comment by azlinda8330** [comment]
sekarang ni saya nak key in data ni

![image](https://user-images.githubusercontent.com/49171338/56095573-e0f85f80-5f10-11e9-8896-2d9588be5bbf.png)

**Comment by azlinda8330** [comment]
Kalau yaakob tengok width dia = 55 m

pastu distance yang pertama ialah jarak 7m ke 8m = 1m

jarak kedua ialah 8 m ke 10 m = 2m

dan seterusnya jarak ialah 2m interval sampai value last sekali 1 m. 

jadi saya nak masuk distance between measurement berapa yer? 1 m ke 2m?

**Comment by azlinda8330** [comment]
Saya cuba masukkan nilai 2

![image](https://user-images.githubusercontent.com/49171338/56095630-55cb9980-5f11-11e9-930d-dc7ae0d9bd63.png)

**Comment by azlinda8330** [comment]
Dia generate 25 vertical columns.

Tapi dalam excel saya kena generate 26 column

**Comment by azlinda8330** [comment]
yaakob, yaakob aware tak yang first column dan last column selalunya akan 1 m and in between baru 2 m interval?

**Comment by azlinda8330** [comment]
@abigoroth

**Comment by abigoroth** [comment]
@azlinda8330 OMG, what is this.. yang saya aware is always the same interval.. en hafiz pun tak ada alert/head up on this

**Comment by abigoroth** [comment]
@azlinda8330 boleh close dulu issue ni?
